// <auto-generated />
using System;
using Equillibrium.QC.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Equillibrium.QC.Infrastructure.Data.Migrations
{
    [DbContext(typeof(QCDbContext))]
    [Migration("20260416211509_InitialQCSetup")]
    partial class InitialQCSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tenants")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Equillibrium.QC.Core.Entities.BatchQcResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchRecordId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsInTolerance")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MeasuredValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<Guid>("SpecificationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TestedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SpecificationId");

                    b.ToTable("BatchQcResults", "tenants");
                });

            modelBuilder.Entity("Equillibrium.QC.Core.Entities.Specification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Parameter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<int>("RouteStage")
                        .HasColumnType("integer");

                    b.Property<decimal>("TargetValue")
                        .HasColumnType("numeric");

                    b.Property<string>("TestMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Specifications", "tenants");
                });

            modelBuilder.Entity("Equillibrium.QC.Core.Entities.BatchQcResult", b =>
                {
                    b.HasOne("Equillibrium.QC.Core.Entities.Specification", "Specification")
                        .WithMany()
                        .HasForeignKey("SpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specification");
                });
#pragma warning restore 612, 618
        }
    }
}
