// <auto-generated />
using System;
using Equillibrium.Manufacturing.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Equillibrium.Manufacturing.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ManufacturingDbContext))]
    partial class ManufacturingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tenants")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Equillibrium.Manufacturing.Core.Entities.BOMItem", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("BOMItems", "tenants");
                });

            modelBuilder.Entity("Equillibrium.Manufacturing.Core.Entities.BatchDeviation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImpactAssessment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LoggedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RequiresManagementSignOff")
                        .HasColumnType("boolean");

                    b.Property<string>("Resolution")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BatchRecordId");

                    b.ToTable("BatchDeviations", "tenants");
                });

            modelBuilder.Entity("Equillibrium.Manufacturing.Core.Entities.BatchMaterialUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MaterialLotId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityUsed")
                        .HasColumnType("numeric");

                    b.Property<string>("ScannedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BatchRecordId");

                    b.HasIndex("MaterialLotId");

                    b.ToTable("BatchMaterialUsages", "tenants");
                });

            modelBuilder.Entity("Equillibrium.Manufacturing.Core.Entities.BatchRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ActualStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ActualYield")
                        .HasColumnType("numeric");

                    b.Property<string>("ApprovalComments")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PlannedQuantity")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecipeVersionAtSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BatchRecords", "tenants");
                });

            modelBuilder.Entity("Equillibrium.Manufacturing.Core.Entities.BatchRouteProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletedByUserId")
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ResultPassed")
                        .HasColumnType("boolean");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<int>("StepType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BatchRecordId");

                    b.ToTable("BatchRouteProgress", "tenants");
                });

            modelBuilder.Entity("Equillibrium.Manufacturing.Core.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("MinimumStockLevel")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ingredients", "tenants");
                });

            modelBuilder.Entity("Equillibrium.Manufacturing.Core.Entities.IngredientSds", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HazardStatements")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastReviewed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SignalWord")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("IngredientSds", "tenants");
                });

            modelBuilder.Entity("Equillibrium.Manufacturing.Core.Entities.Instruction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetailedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelatedBOMItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TargetValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Instructions", "tenants");
                });

            modelBuilder.Entity("Equillibrium.Manufacturing.Core.Entities.MaterialLot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostAtPurchase")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<string>("InternalBatchNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("QuantityReceived")
                        .HasColumnType("numeric");

                    b.Property<decimal>("QuantityRemaining")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SupplierLotNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("SupplierLotNo");

                    b.ToTable("MaterialLots", "tenants");
                });

            modelBuilder.Entity("Equillibrium.Manufacturing.Core.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Recipes", "tenants");
                });

            modelBuilder.Entity("Equillibrium.Manufacturing.Core.Entities.RouteStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RequiresSignOff")
                        .HasColumnType("boolean");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RouteSteps", "tenants");
                });

            modelBuilder.Entity("Equillibrium.Manufacturing.Core.Entities.BOMItem", b =>
                {
                    b.HasOne("Equillibrium.Manufacturing.Core.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Equillibrium.Manufacturing.Core.Entities.Recipe", null)
                        .WithMany("BillOfMaterials")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Equillibrium.Manufacturing.Core.Entities.BatchDeviation", b =>
                {
                    b.HasOne("Equillibrium.Manufacturing.Core.Entities.BatchRecord", null)
                        .WithMany("Deviations")
                        .HasForeignKey("BatchRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Equillibrium.Manufacturing.Core.Entities.BatchMaterialUsage", b =>
                {
                    b.HasOne("Equillibrium.Manufacturing.Core.Entities.BatchRecord", null)
                        .WithMany("ActualMaterialUsage")
                        .HasForeignKey("BatchRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Equillibrium.Manufacturing.Core.Entities.MaterialLot", "MaterialLot")
                        .WithMany()
                        .HasForeignKey("MaterialLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialLot");
                });

            modelBuilder.Entity("Equillibrium.Manufacturing.Core.Entities.BatchRouteProgress", b =>
                {
                    b.HasOne("Equillibrium.Manufacturing.Core.Entities.BatchRecord", null)
                        .WithMany("RouteProgress")
                        .HasForeignKey("BatchRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Equillibrium.Manufacturing.Core.Entities.Instruction", b =>
                {
                    b.HasOne("Equillibrium.Manufacturing.Core.Entities.Recipe", null)
                        .WithMany("Instructions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Equillibrium.Manufacturing.Core.Entities.MaterialLot", b =>
                {
                    b.HasOne("Equillibrium.Manufacturing.Core.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Equillibrium.Manufacturing.Core.Entities.RouteStep", b =>
                {
                    b.HasOne("Equillibrium.Manufacturing.Core.Entities.Recipe", null)
                        .WithMany("DefaultRoute")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Equillibrium.Manufacturing.Core.Entities.BatchRecord", b =>
                {
                    b.Navigation("ActualMaterialUsage");

                    b.Navigation("Deviations");

                    b.Navigation("RouteProgress");
                });

            modelBuilder.Entity("Equillibrium.Manufacturing.Core.Entities.Recipe", b =>
                {
                    b.Navigation("BillOfMaterials");

                    b.Navigation("DefaultRoute");

                    b.Navigation("Instructions");
                });
#pragma warning restore 612, 618
        }
    }
}
